# Generated by Django 2.1 on 2018-10-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile_teacher',
        ),
    ]
