# Generated by Django 2.1 on 2018-10-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_auto_20181021_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
