# Generated by Django 2.1 on 2018-10-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_assignment_and_class_assignments_by_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_in_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=1000)),
                ('class_name', models.CharField(max_length=500)),
            ],
        ),
    ]
