# Generated by Django 2.1 on 2018-10-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_in_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments_by_teacher',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher_in_class'),
        ),
    ]
