# Generated by Django 2.1 on 2018-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20181021_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments_by_teacher',
            name='teacher_name',
            field=models.CharField(max_length=200),
        ),
    ]
