# Generated by Django 2.1 on 2018-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(max_length=200)),
                ('s_fullname', models.CharField(max_length=200)),
                ('s_email', models.CharField(max_length=200)),
                ('s_rollno', models.CharField(max_length=200)),
                ('s_class', models.CharField(max_length=200)),
                ('s_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_in_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_mpi', models.CharField(max_length=200)),
                ('class_ict', models.CharField(max_length=200)),
                ('class_dm', models.CharField(max_length=200)),
                ('class_ds', models.CharField(max_length=200)),
                ('class_coa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='teacherdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_username', models.CharField(max_length=200)),
                ('t_fullname', models.CharField(max_length=200)),
                ('t_email', models.CharField(max_length=200)),
                ('t_subject', models.CharField(max_length=200)),
                ('t_password', models.CharField(max_length=200)),
            ],
        ),
    ]
