# Generated by Django 2.1 on 2018-10-02 10:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_by_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
    ]
