# Generated by Django 2.1 on 2018-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_assignment_by_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_by_student',
            name='assignment_content',
        ),
        migrations.AddField(
            model_name='assignment_by_student',
            name='content',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
