# Generated by Django 2.1 on 2018-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20181002_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_by_student',
            name='user',
            field=models.CharField(default='User0', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignment_by_student',
            name='content',
            field=models.CharField(default='EMPTY STRING', max_length=2000),
        ),
    ]
