# Generated by Django 2.1 on 2018-10-08 13:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20181002_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_by_student',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
