# Generated by Django 2.1 on 2018-10-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20181008_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_by_student',
            name='content',
            field=models.CharField(default='User0', max_length=20000),
        ),
    ]
