# Generated by Django 2.1 on 2018-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20181019_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='s_rollno',
            field=models.IntegerField(max_length=200),
        ),
    ]
