# Generated by Django 2.1 on 2018-10-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20181019_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='s_rollno',
            field=models.IntegerField(),
        ),
    ]
