# Generated by Django 2.1 on 2018-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_auto_20181020_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='s_rollno',
            field=models.IntegerField(null=True),
        ),
    ]
