# Generated by Django 2.1 on 2018-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20181020_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isTeacher',
            field=models.BooleanField(default=True),
        ),
    ]
