# Generated by Django 2.1 on 2018-10-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_profile_isteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isTeacher',
        ),
    ]
