# Generated by Django 2.1 on 2018-10-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0014_remove_profile_isteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdb',
            name='t_subject',
        ),
    ]
