# Generated by Django 2.1 on 2018-10-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_remove_teacherdb_t_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_by_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('ass_title', models.CharField(max_length=500)),
                ('ass_body', models.CharField(max_length=5000)),
                ('ass_date', models.DateField()),
                ('ass_sub_date', models.DateField()),
                ('extra_note', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
