# Generated by Django 2.1 on 2018-10-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
