# Generated by Django 2.1 on 2018-10-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0019_profile_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile_teacher',
        ),
    ]
