# Generated by Django 2.1 on 2018-10-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0020_auto_20181020_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='s_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
