# Generated by Django 2.1 on 2018-10-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0021_auto_20181021_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher_in_class',
        ),
        migrations.DeleteModel(
            name='teacherdb',
        ),
    ]
