# Generated by Django 2.1 on 2018-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0023_auto_20181021_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment_submitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('ass_title', models.CharField(max_length=1000)),
                ('submit_date', models.DateField()),
                ('plag_ratio', models.IntegerField()),
            ],
        ),
    ]
