# Generated by Django 2.1 on 2018-10-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0024_assignment_submitted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assignments_by_teacher',
        ),
    ]
