# Generated by Django 2.1.4 on 2018-12-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0027_assignment_submitted_s_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='s_bio',
            field=models.CharField(blank=True, default='No Bio', max_length=200, null=True),
        ),
    ]
