# Generated by Django 2.1.4 on 2018-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0028_profile_s_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_save',
            name='content',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='assignment_submitted',
            name='plag_ratio',
            field=models.IntegerField(default=0),
        ),
    ]
